// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: code_tests.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCodeTest = `-- name: CreateCodeTest :one
INSERT INTO code_tests (id, txt_input, file_input, expected_output, created_at, updated_at, previous_test_id, next_test_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, txt_input, file_input, expected_output, created_at, updated_at, next_test_id, previous_test_id
`

type CreateCodeTestParams struct {
	ID             uuid.UUID
	TxtInput       sql.NullString
	FileInput      uuid.NullUUID
	ExpectedOutput string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	PreviousTestID uuid.NullUUID
	NextTestID     uuid.NullUUID
}

func (q *Queries) CreateCodeTest(ctx context.Context, arg CreateCodeTestParams) (CodeTest, error) {
	row := q.db.QueryRowContext(ctx, createCodeTest,
		arg.ID,
		arg.TxtInput,
		arg.FileInput,
		arg.ExpectedOutput,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PreviousTestID,
		arg.NextTestID,
	)
	var i CodeTest
	err := row.Scan(
		&i.ID,
		&i.TxtInput,
		&i.FileInput,
		&i.ExpectedOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextTestID,
		&i.PreviousTestID,
	)
	return i, err
}

const deleteCodeTestByID = `-- name: DeleteCodeTestByID :exec
DELETE FROM code_tests
WHERE id = $1
`

func (q *Queries) DeleteCodeTestByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCodeTestByID, id)
	return err
}

const getCodeTestByID = `-- name: GetCodeTestByID :one
SELECT id, txt_input, file_input, expected_output, created_at, updated_at, next_test_id, previous_test_id FROM code_tests
WHERE id = $1
`

func (q *Queries) GetCodeTestByID(ctx context.Context, id uuid.UUID) (CodeTest, error) {
	row := q.db.QueryRowContext(ctx, getCodeTestByID, id)
	var i CodeTest
	err := row.Scan(
		&i.ID,
		&i.TxtInput,
		&i.FileInput,
		&i.ExpectedOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextTestID,
		&i.PreviousTestID,
	)
	return i, err
}

const listAllCodeTests = `-- name: ListAllCodeTests :many
SELECT id, txt_input, file_input, expected_output, created_at, updated_at, next_test_id, previous_test_id FROM code_tests
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListAllCodeTestsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAllCodeTests(ctx context.Context, arg ListAllCodeTestsParams) ([]CodeTest, error) {
	rows, err := q.db.QueryContext(ctx, listAllCodeTests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeTest
	for rows.Next() {
		var i CodeTest
		if err := rows.Scan(
			&i.ID,
			&i.TxtInput,
			&i.FileInput,
			&i.ExpectedOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextTestID,
			&i.PreviousTestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodeTestsByIDs = `-- name: ListCodeTestsByIDs :many
SELECT id, txt_input, file_input, expected_output, created_at, updated_at, next_test_id, previous_test_id FROM code_tests
WHERE id = ANY($1)
`

func (q *Queries) ListCodeTestsByIDs(ctx context.Context, id uuid.UUID) ([]CodeTest, error) {
	rows, err := q.db.QueryContext(ctx, listCodeTestsByIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeTest
	for rows.Next() {
		var i CodeTest
		if err := rows.Scan(
			&i.ID,
			&i.TxtInput,
			&i.FileInput,
			&i.ExpectedOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextTestID,
			&i.PreviousTestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCodeTestExpectedOutput = `-- name: UpdateCodeTestExpectedOutput :one
UPDATE code_tests
SET expected_output = $2,
    updated_at = $3
WHERE id = $1
RETURNING id, txt_input, file_input, expected_output, created_at, updated_at, next_test_id, previous_test_id
`

type UpdateCodeTestExpectedOutputParams struct {
	ID             uuid.UUID
	ExpectedOutput string
	UpdatedAt      time.Time
}

func (q *Queries) UpdateCodeTestExpectedOutput(ctx context.Context, arg UpdateCodeTestExpectedOutputParams) (CodeTest, error) {
	row := q.db.QueryRowContext(ctx, updateCodeTestExpectedOutput, arg.ID, arg.ExpectedOutput, arg.UpdatedAt)
	var i CodeTest
	err := row.Scan(
		&i.ID,
		&i.TxtInput,
		&i.FileInput,
		&i.ExpectedOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextTestID,
		&i.PreviousTestID,
	)
	return i, err
}

const updateCodeTestInputs = `-- name: UpdateCodeTestInputs :one
UPDATE code_tests
SET txt_input = $2,
    file_input = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, txt_input, file_input, expected_output, created_at, updated_at, next_test_id, previous_test_id
`

type UpdateCodeTestInputsParams struct {
	ID        uuid.UUID
	TxtInput  sql.NullString
	FileInput uuid.NullUUID
	UpdatedAt time.Time
}

func (q *Queries) UpdateCodeTestInputs(ctx context.Context, arg UpdateCodeTestInputsParams) (CodeTest, error) {
	row := q.db.QueryRowContext(ctx, updateCodeTestInputs,
		arg.ID,
		arg.TxtInput,
		arg.FileInput,
		arg.UpdatedAt,
	)
	var i CodeTest
	err := row.Scan(
		&i.ID,
		&i.TxtInput,
		&i.FileInput,
		&i.ExpectedOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextTestID,
		&i.PreviousTestID,
	)
	return i, err
}

const updateNextCodeTest = `-- name: UpdateNextCodeTest :one
UPDATE code_tests
SET next_test_id = $2,
    updated_at = $3
WHERE id = $1
RETURNING id, txt_input, file_input, expected_output, created_at, updated_at, next_test_id, previous_test_id
`

type UpdateNextCodeTestParams struct {
	ID         uuid.UUID
	NextTestID uuid.NullUUID
	UpdatedAt  time.Time
}

func (q *Queries) UpdateNextCodeTest(ctx context.Context, arg UpdateNextCodeTestParams) (CodeTest, error) {
	row := q.db.QueryRowContext(ctx, updateNextCodeTest, arg.ID, arg.NextTestID, arg.UpdatedAt)
	var i CodeTest
	err := row.Scan(
		&i.ID,
		&i.TxtInput,
		&i.FileInput,
		&i.ExpectedOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextTestID,
		&i.PreviousTestID,
	)
	return i, err
}

const updatePreviousCodeTest = `-- name: UpdatePreviousCodeTest :one
UPDATE code_tests
SET previous_test_id = $2,
    updated_at = $3
WHERE id = $1
RETURNING id, txt_input, file_input, expected_output, created_at, updated_at, next_test_id, previous_test_id
`

type UpdatePreviousCodeTestParams struct {
	ID             uuid.UUID
	PreviousTestID uuid.NullUUID
	UpdatedAt      time.Time
}

func (q *Queries) UpdatePreviousCodeTest(ctx context.Context, arg UpdatePreviousCodeTestParams) (CodeTest, error) {
	row := q.db.QueryRowContext(ctx, updatePreviousCodeTest, arg.ID, arg.PreviousTestID, arg.UpdatedAt)
	var i CodeTest
	err := row.Scan(
		&i.ID,
		&i.TxtInput,
		&i.FileInput,
		&i.ExpectedOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextTestID,
		&i.PreviousTestID,
	)
	return i, err
}
