// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboard.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLeaderboard = `-- name: CreateLeaderboard :one
INSERT INTO leaderboard (user_id, score, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, score, created_at, updated_at
`

type CreateLeaderboardParams struct {
	UserID    uuid.UUID
	Score     int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateLeaderboard(ctx context.Context, arg CreateLeaderboardParams) (Leaderboard, error) {
	row := q.db.QueryRowContext(ctx, createLeaderboard,
		arg.UserID,
		arg.Score,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Leaderboard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLeaderboardByUserID = `-- name: DeleteLeaderboardByUserID :exec
DELETE FROM leaderboard
WHERE user_id = $1
`

func (q *Queries) DeleteLeaderboardByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLeaderboardByUserID, userID)
	return err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT id, user_id, score, created_at, updated_at FROM leaderboard
ORDER BY score DESC, created_at ASC
LIMIT $1 OFFSET $2
`

type GetLeaderboardParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]Leaderboard, error) {
	rows, err := q.db.QueryContext(ctx, getLeaderboard, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Leaderboard
	for rows.Next() {
		var i Leaderboard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Score,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardAroundUser = `-- name: GetLeaderboardAroundUser :many
WITH ranked_leaderboard AS (
    SELECT id, user_id, score, created_at, updated_at, ROW_NUMBER() OVER (ORDER BY score DESC, created_at ASC) as PLACEMENT
    FROM leaderboard
)
SELECT id, user_id, score, created_at, updated_at, placement FROM ranked_leaderboard
WHERE PLACEMENT BETWEEN GREATEST((SELECT PLACEMENT FROM ranked_leaderboard WHERE user_id = $1) - 2, 1) AND (SELECT PLACEMENT FROM ranked_leaderboard WHERE user_id = $1) + 2
ORDER BY PLACEMENT ASC
`

type GetLeaderboardAroundUserRow struct {
	ID        int32
	UserID    uuid.UUID
	Score     int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Placement int64
}

func (q *Queries) GetLeaderboardAroundUser(ctx context.Context, userID uuid.UUID) ([]GetLeaderboardAroundUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeaderboardAroundUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardAroundUserRow
	for rows.Next() {
		var i GetLeaderboardAroundUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Score,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Placement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardByUserID = `-- name: GetLeaderboardByUserID :one
SELECT id, user_id, score, created_at, updated_at, ROW_NUMBER() OVER (ORDER BY score DESC, created_at ASC) as PLACEMENT FROM leaderboard
WHERE user_id = $1
`

type GetLeaderboardByUserIDRow struct {
	ID        int32
	UserID    uuid.UUID
	Score     int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Placement int64
}

func (q *Queries) GetLeaderboardByUserID(ctx context.Context, userID uuid.UUID) (GetLeaderboardByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLeaderboardByUserID, userID)
	var i GetLeaderboardByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Placement,
	)
	return i, err
}

const getLeaderboardCount = `-- name: GetLeaderboardCount :one
SELECT COUNT(*) FROM leaderboard
`

func (q *Queries) GetLeaderboardCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLeaderboardCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateLeaderboardScore = `-- name: UpdateLeaderboardScore :one
UPDATE leaderboard
SET score = $2, updated_at = $3
WHERE user_id = $1
RETURNING id, user_id, score, created_at, updated_at
`

type UpdateLeaderboardScoreParams struct {
	UserID    uuid.UUID
	Score     int32
	UpdatedAt time.Time
}

func (q *Queries) UpdateLeaderboardScore(ctx context.Context, arg UpdateLeaderboardScoreParams) (Leaderboard, error) {
	row := q.db.QueryRowContext(ctx, updateLeaderboardScore, arg.UserID, arg.Score, arg.UpdatedAt)
	var i Leaderboard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
