// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lessons_users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countLessonsUsersFavoritedLessonsByLessonID = `-- name: CountLessonsUsersFavoritedLessonsByLessonID :one
SELECT COUNT(*) FROM lessons_users
WHERE lesson_id = $1 AND favorited = TRUE
`

func (q *Queries) CountLessonsUsersFavoritedLessonsByLessonID(ctx context.Context, lessonID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLessonsUsersFavoritedLessonsByLessonID, lessonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLessonsUsers = `-- name: CreateLessonsUsers :one
INSERT INTO lessons_users (lesson_id, user_id, favorited, bookmarked, started_at, completed_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, lesson_id, user_id, favorited, bookmarked, started_at, completed_at, created_at, updated_at
`

type CreateLessonsUsersParams struct {
	LessonID    uuid.UUID
	UserID      uuid.UUID
	Favorited   sql.NullBool
	Bookmarked  sql.NullBool
	StartedAt   sql.NullTime
	CompletedAt sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) CreateLessonsUsers(ctx context.Context, arg CreateLessonsUsersParams) (LessonsUser, error) {
	row := q.db.QueryRowContext(ctx, createLessonsUsers,
		arg.LessonID,
		arg.UserID,
		arg.Favorited,
		arg.Bookmarked,
		arg.StartedAt,
		arg.CompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LessonsUser
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.UserID,
		&i.Favorited,
		&i.Bookmarked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLessonsUsersByLessonIDAndUserID = `-- name: DeleteLessonsUsersByLessonIDAndUserID :exec
DELETE FROM lessons_users
WHERE lesson_id = $1 AND user_id = $2
`

type DeleteLessonsUsersByLessonIDAndUserIDParams struct {
	LessonID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) DeleteLessonsUsersByLessonIDAndUserID(ctx context.Context, arg DeleteLessonsUsersByLessonIDAndUserIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteLessonsUsersByLessonIDAndUserID, arg.LessonID, arg.UserID)
	return err
}

const getLessonsUsersBookmarkedLessonsByUserID = `-- name: GetLessonsUsersBookmarkedLessonsByUserID :many
SELECT id, lesson_id, user_id, favorited, bookmarked, started_at, completed_at, created_at, updated_at FROM lessons_users
WHERE user_id = $1 AND bookmarked = TRUE
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type GetLessonsUsersBookmarkedLessonsByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetLessonsUsersBookmarkedLessonsByUserID(ctx context.Context, arg GetLessonsUsersBookmarkedLessonsByUserIDParams) ([]LessonsUser, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsUsersBookmarkedLessonsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonsUser
	for rows.Next() {
		var i LessonsUser
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.UserID,
			&i.Favorited,
			&i.Bookmarked,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonsUsersByLessonID = `-- name: GetLessonsUsersByLessonID :many
SELECT id, lesson_id, user_id, favorited, bookmarked, started_at, completed_at, created_at, updated_at FROM lessons_users
WHERE lesson_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetLessonsUsersByLessonIDParams struct {
	LessonID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) GetLessonsUsersByLessonID(ctx context.Context, arg GetLessonsUsersByLessonIDParams) ([]LessonsUser, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsUsersByLessonID, arg.LessonID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonsUser
	for rows.Next() {
		var i LessonsUser
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.UserID,
			&i.Favorited,
			&i.Bookmarked,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonsUsersByLessonIDAndUserID = `-- name: GetLessonsUsersByLessonIDAndUserID :one
SELECT id, lesson_id, user_id, favorited, bookmarked, started_at, completed_at, created_at, updated_at FROM lessons_users
WHERE lesson_id = $1 AND user_id = $2
`

type GetLessonsUsersByLessonIDAndUserIDParams struct {
	LessonID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetLessonsUsersByLessonIDAndUserID(ctx context.Context, arg GetLessonsUsersByLessonIDAndUserIDParams) (LessonsUser, error) {
	row := q.db.QueryRowContext(ctx, getLessonsUsersByLessonIDAndUserID, arg.LessonID, arg.UserID)
	var i LessonsUser
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.UserID,
		&i.Favorited,
		&i.Bookmarked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLessonsUsersByUserID = `-- name: GetLessonsUsersByUserID :many
SELECT id, lesson_id, user_id, favorited, bookmarked, started_at, completed_at, created_at, updated_at FROM lessons_users
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetLessonsUsersByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetLessonsUsersByUserID(ctx context.Context, arg GetLessonsUsersByUserIDParams) ([]LessonsUser, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsUsersByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonsUser
	for rows.Next() {
		var i LessonsUser
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.UserID,
			&i.Favorited,
			&i.Bookmarked,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonsUsersCompletedLessonsByUserID = `-- name: GetLessonsUsersCompletedLessonsByUserID :many
SELECT id, lesson_id, user_id, favorited, bookmarked, started_at, completed_at, created_at, updated_at FROM lessons_users
WHERE user_id = $1 AND completed_at IS NOT NULL
ORDER BY completed_at DESC
LIMIT $2 OFFSET $3
`

type GetLessonsUsersCompletedLessonsByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetLessonsUsersCompletedLessonsByUserID(ctx context.Context, arg GetLessonsUsersCompletedLessonsByUserIDParams) ([]LessonsUser, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsUsersCompletedLessonsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonsUser
	for rows.Next() {
		var i LessonsUser
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.UserID,
			&i.Favorited,
			&i.Bookmarked,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonsUsersFavoritedLessonsByUserID = `-- name: GetLessonsUsersFavoritedLessonsByUserID :many
SELECT id, lesson_id, user_id, favorited, bookmarked, started_at, completed_at, created_at, updated_at FROM lessons_users
WHERE user_id = $1 AND favorited = TRUE
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type GetLessonsUsersFavoritedLessonsByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetLessonsUsersFavoritedLessonsByUserID(ctx context.Context, arg GetLessonsUsersFavoritedLessonsByUserIDParams) ([]LessonsUser, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsUsersFavoritedLessonsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonsUser
	for rows.Next() {
		var i LessonsUser
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.UserID,
			&i.Favorited,
			&i.Bookmarked,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonsUsersStartedLessonsByUserID = `-- name: GetLessonsUsersStartedLessonsByUserID :many
SELECT id, lesson_id, user_id, favorited, bookmarked, started_at, completed_at, created_at, updated_at FROM lessons_users
WHERE user_id = $1 AND started_at IS NOT NULL AND completed_at IS NULL
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type GetLessonsUsersStartedLessonsByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetLessonsUsersStartedLessonsByUserID(ctx context.Context, arg GetLessonsUsersStartedLessonsByUserIDParams) ([]LessonsUser, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsUsersStartedLessonsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonsUser
	for rows.Next() {
		var i LessonsUser
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.UserID,
			&i.Favorited,
			&i.Bookmarked,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLessonsUsersBookmarked = `-- name: UpdateLessonsUsersBookmarked :one
UPDATE lessons_users
SET bookmarked = $1, updated_at = $2
WHERE lesson_id = $3 AND user_id = $4
RETURNING id, lesson_id, user_id, favorited, bookmarked, started_at, completed_at, created_at, updated_at
`

type UpdateLessonsUsersBookmarkedParams struct {
	Bookmarked sql.NullBool
	UpdatedAt  sql.NullTime
	LessonID   uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) UpdateLessonsUsersBookmarked(ctx context.Context, arg UpdateLessonsUsersBookmarkedParams) (LessonsUser, error) {
	row := q.db.QueryRowContext(ctx, updateLessonsUsersBookmarked,
		arg.Bookmarked,
		arg.UpdatedAt,
		arg.LessonID,
		arg.UserID,
	)
	var i LessonsUser
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.UserID,
		&i.Favorited,
		&i.Bookmarked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLessonsUsersComplete = `-- name: UpdateLessonsUsersComplete :one
UPDATE lessons_users
SET completed_at = $1, updated_at = $2
WHERE lesson_id = $3 AND user_id = $4
RETURNING id, lesson_id, user_id, favorited, bookmarked, started_at, completed_at, created_at, updated_at
`

type UpdateLessonsUsersCompleteParams struct {
	CompletedAt sql.NullTime
	UpdatedAt   sql.NullTime
	LessonID    uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateLessonsUsersComplete(ctx context.Context, arg UpdateLessonsUsersCompleteParams) (LessonsUser, error) {
	row := q.db.QueryRowContext(ctx, updateLessonsUsersComplete,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.LessonID,
		arg.UserID,
	)
	var i LessonsUser
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.UserID,
		&i.Favorited,
		&i.Bookmarked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLessonsUsersFavorited = `-- name: UpdateLessonsUsersFavorited :one
UPDATE lessons_users
SET favorited = $1, updated_at = $2
WHERE lesson_id = $3 AND user_id = $4
RETURNING id, lesson_id, user_id, favorited, bookmarked, started_at, completed_at, created_at, updated_at
`

type UpdateLessonsUsersFavoritedParams struct {
	Favorited sql.NullBool
	UpdatedAt sql.NullTime
	LessonID  uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) UpdateLessonsUsersFavorited(ctx context.Context, arg UpdateLessonsUsersFavoritedParams) (LessonsUser, error) {
	row := q.db.QueryRowContext(ctx, updateLessonsUsersFavorited,
		arg.Favorited,
		arg.UpdatedAt,
		arg.LessonID,
		arg.UserID,
	)
	var i LessonsUser
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.UserID,
		&i.Favorited,
		&i.Bookmarked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLessonsUsersStart = `-- name: UpdateLessonsUsersStart :one
UPDATE lessons_users
SET started_at = $1, updated_at = $2
WHERE lesson_id = $3 AND user_id = $4
RETURNING id, lesson_id, user_id, favorited, bookmarked, started_at, completed_at, created_at, updated_at
`

type UpdateLessonsUsersStartParams struct {
	StartedAt sql.NullTime
	UpdatedAt sql.NullTime
	LessonID  uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) UpdateLessonsUsersStart(ctx context.Context, arg UpdateLessonsUsersStartParams) (LessonsUser, error) {
	row := q.db.QueryRowContext(ctx, updateLessonsUsersStart,
		arg.StartedAt,
		arg.UpdatedAt,
		arg.LessonID,
		arg.UserID,
	)
	var i LessonsUser
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.UserID,
		&i.Favorited,
		&i.Bookmarked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
