// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lessons.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addLesson = `-- name: AddLesson :one
INSERT INTO lessons (id, title, description, author_id, content_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id
`

type AddLessonParams struct {
	ID           uuid.UUID
	Title        string
	Description  sql.NullString
	AuthorID     uuid.NullUUID
	ContentID    uuid.UUID
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	Flags        int32
	NextLessonID uuid.NullUUID
	PrevLessonID uuid.NullUUID
}

func (q *Queries) AddLesson(ctx context.Context, arg AddLessonParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, addLesson,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AuthorID,
		arg.ContentID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Flags,
		arg.NextLessonID,
		arg.PrevLessonID,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
	)
	return i, err
}

const countLessons = `-- name: CountLessons :one
SELECT COUNT(*) FROM lessons
WHERE flags & $1 = $2
`

type CountLessonsParams struct {
	Flags   int32
	Flags_2 int32
}

// the following query counts the number of lessons with flags matching a given bitmask
func (q *Queries) CountLessons(ctx context.Context, arg CountLessonsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLessons, arg.Flags, arg.Flags_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLessonByContentID = `-- name: GetLessonByContentID :one
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id FROM lessons
WHERE content_id = $1
`

func (q *Queries) GetLessonByContentID(ctx context.Context, contentID uuid.UUID) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLessonByContentID, contentID)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
	)
	return i, err
}

const getLessonByFlags = `-- name: GetLessonByFlags :one
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id FROM lessons
WHERE flags = $1
`

func (q *Queries) GetLessonByFlags(ctx context.Context, flags int32) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLessonByFlags, flags)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
	)
	return i, err
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id FROM lessons
WHERE id = $1
`

func (q *Queries) GetLessonByID(ctx context.Context, id uuid.UUID) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLessonByID, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
	)
	return i, err
}

const getLessons = `-- name: GetLessons :many
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id FROM lessons
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetLessonsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetLessons(ctx context.Context, arg GetLessonsParams) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, getLessons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flags,
			&i.NextLessonID,
			&i.PrevLessonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
