// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lessons.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addLesson = `-- name: AddLesson :one
INSERT INTO lessons (id, title, description, author_id, content_id, created_at, updated_at, flags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, description, content_id, author_id, created_at, updated_at, flags
`

type AddLessonParams struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	AuthorID    uuid.NullUUID
	ContentID   uuid.UUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Flags       int32
}

func (q *Queries) AddLesson(ctx context.Context, arg AddLessonParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, addLesson,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AuthorID,
		arg.ContentID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Flags,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
	)
	return i, err
}

const getAllLessons = `-- name: GetAllLessons :many
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags FROM lessons
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllLessonsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllLessons(ctx context.Context, arg GetAllLessonsParams) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, getAllLessons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonByFlags = `-- name: GetLessonByFlags :one
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags FROM lessons
WHERE flags = $1
`

func (q *Queries) GetLessonByFlags(ctx context.Context, flags int32) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLessonByFlags, flags)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
	)
	return i, err
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags FROM lessons
WHERE id = $1
`

func (q *Queries) GetLessonByID(ctx context.Context, id uuid.UUID) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLessonByID, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
	)
	return i, err
}
