// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lessons.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addLesson = `-- name: AddLesson :one
INSERT INTO lessons (id, title, description, author_id, content_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, suggested, thumbnail_id, language)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language
`

type AddLessonParams struct {
	ID           uuid.UUID
	Title        string
	Description  sql.NullString
	AuthorID     uuid.NullUUID
	ContentID    uuid.UUID
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	Flags        int32
	NextLessonID uuid.NullUUID
	PrevLessonID uuid.NullUUID
	Suggested    bool
	ThumbnailID  uuid.NullUUID
	Language     string
}

func (q *Queries) AddLesson(ctx context.Context, arg AddLessonParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, addLesson,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AuthorID,
		arg.ContentID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Flags,
		arg.NextLessonID,
		arg.PrevLessonID,
		arg.Suggested,
		arg.ThumbnailID,
		arg.Language,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
		&i.SectionStarter,
		&i.Suggested,
		&i.ThumbnailID,
		&i.Language,
	)
	return i, err
}

const countLessons = `-- name: CountLessons :one
SELECT COUNT(*) FROM lessons
WHERE flags & $1 = $2 and suggested = FALSE
`

type CountLessonsParams struct {
	Flags   int32
	Flags_2 int32
}

// the following query counts the number of lessons with flags matching a given bitmask
func (q *Queries) CountLessons(ctx context.Context, arg CountLessonsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLessons, arg.Flags, arg.Flags_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLessonsByUniqueSections = `-- name: CountLessonsByUniqueSections :one
SELECT COUNT(*) FROM (
    SELECT DISTINCT flags & 65280 AS section_flag
    FROM lessons
    WHERE section_starter = TRUE
) AS unique_sections
`

func (q *Queries) CountLessonsByUniqueSections(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLessonsByUniqueSections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLessonByID = `-- name: DeleteLessonByID :exec
DELETE FROM lessons
WHERE id = $1
`

func (q *Queries) DeleteLessonByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLessonByID, id)
	return err
}

const getAllLessonsFromSectionStarter = `-- name: GetAllLessonsFromSectionStarter :many
WITH RECURSIVE lesson_chain AS (
    SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language
    FROM lessons f
    WHERE f.id = $1
    UNION ALL
    SELECT l.id, l.title, l.description, l.content_id, l.author_id, l.created_at, l.updated_at, l.flags, l.next_lesson_id, l.prev_lesson_id, l.section_starter, l.suggested, l.thumbnail_id, l.language
    FROM lessons l
    INNER JOIN lesson_chain lc ON l.id = lc.next_lesson_id
)
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language FROM lesson_chain
ORDER BY created_at ASC
`

type GetAllLessonsFromSectionStarterRow struct {
	ID             uuid.UUID
	Title          string
	Description    sql.NullString
	ContentID      uuid.UUID
	AuthorID       uuid.NullUUID
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Flags          int32
	NextLessonID   uuid.NullUUID
	PrevLessonID   uuid.NullUUID
	SectionStarter bool
	Suggested      bool
	ThumbnailID    uuid.NullUUID
	Language       string
}

func (q *Queries) GetAllLessonsFromSectionStarter(ctx context.Context, id uuid.UUID) ([]GetAllLessonsFromSectionStarterRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllLessonsFromSectionStarter, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLessonsFromSectionStarterRow
	for rows.Next() {
		var i GetAllLessonsFromSectionStarterRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flags,
			&i.NextLessonID,
			&i.PrevLessonID,
			&i.SectionStarter,
			&i.Suggested,
			&i.ThumbnailID,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonByContentID = `-- name: GetLessonByContentID :one
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language FROM lessons
WHERE content_id = $1
`

func (q *Queries) GetLessonByContentID(ctx context.Context, contentID uuid.UUID) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLessonByContentID, contentID)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
		&i.SectionStarter,
		&i.Suggested,
		&i.ThumbnailID,
		&i.Language,
	)
	return i, err
}

const getLessonByFlags = `-- name: GetLessonByFlags :one
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language FROM lessons
WHERE flags = $1 and suggested = FALSE
`

func (q *Queries) GetLessonByFlags(ctx context.Context, flags int32) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLessonByFlags, flags)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
		&i.SectionStarter,
		&i.Suggested,
		&i.ThumbnailID,
		&i.Language,
	)
	return i, err
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language FROM lessons
WHERE id = $1
`

func (q *Queries) GetLessonByID(ctx context.Context, id uuid.UUID) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLessonByID, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
		&i.SectionStarter,
		&i.Suggested,
		&i.ThumbnailID,
		&i.Language,
	)
	return i, err
}

const getLessons = `-- name: GetLessons :many
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language FROM lessons
WHERE suggested = FALSE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetLessonsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetLessons(ctx context.Context, arg GetLessonsParams) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, getLessons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flags,
			&i.NextLessonID,
			&i.PrevLessonID,
			&i.SectionStarter,
			&i.Suggested,
			&i.ThumbnailID,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonsByAuthorID = `-- name: GetLessonsByAuthorID :many
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language FROM lessons
WHERE author_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetLessonsByAuthorIDParams struct {
	AuthorID uuid.NullUUID
	Limit    int32
	Offset   int32
}

func (q *Queries) GetLessonsByAuthorID(ctx context.Context, arg GetLessonsByAuthorIDParams) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsByAuthorID, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flags,
			&i.NextLessonID,
			&i.PrevLessonID,
			&i.SectionStarter,
			&i.Suggested,
			&i.ThumbnailID,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonsByFlags = `-- name: GetLessonsByFlags :many
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language FROM lessons
WHERE flags & $1 = $2 and suggested = FALSE
ORDER BY flags ASC, created_at DESC
LIMIT $3 OFFSET $4
`

type GetLessonsByFlagsParams struct {
	Flags   int32
	Flags_2 int32
	Limit   int32
	Offset  int32
}

func (q *Queries) GetLessonsByFlags(ctx context.Context, arg GetLessonsByFlagsParams) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsByFlags,
		arg.Flags,
		arg.Flags_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flags,
			&i.NextLessonID,
			&i.PrevLessonID,
			&i.SectionStarter,
			&i.Suggested,
			&i.ThumbnailID,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonsByLanguage = `-- name: GetLessonsByLanguage :many
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language FROM lessons
WHERE language = $1 and suggested = FALSE
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetLessonsByLanguageParams struct {
	Language string
	Limit    int32
	Offset   int32
}

func (q *Queries) GetLessonsByLanguage(ctx context.Context, arg GetLessonsByLanguageParams) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsByLanguage, arg.Language, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flags,
			&i.NextLessonID,
			&i.PrevLessonID,
			&i.SectionStarter,
			&i.Suggested,
			&i.ThumbnailID,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectionStarterLessons = `-- name: GetSectionStarterLessons :many
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language FROM lessons
WHERE section_starter = TRUE
ORDER BY section_starter ASC
`

func (q *Queries) GetSectionStarterLessons(ctx context.Context) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, getSectionStarterLessons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flags,
			&i.NextLessonID,
			&i.PrevLessonID,
			&i.SectionStarter,
			&i.Suggested,
			&i.ThumbnailID,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuggestedLessons = `-- name: GetSuggestedLessons :many
SELECT id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language FROM lessons
WHERE suggested = TRUE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetSuggestedLessonsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetSuggestedLessons(ctx context.Context, arg GetSuggestedLessonsParams) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, getSuggestedLessons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flags,
			&i.NextLessonID,
			&i.PrevLessonID,
			&i.SectionStarter,
			&i.Suggested,
			&i.ThumbnailID,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetSectionStarterForSection = `-- name: ResetSectionStarterForSection :exec
UPDATE lessons
SET section_starter = FALSE
WHERE flags & 65280 = $1
`

func (q *Queries) ResetSectionStarterForSection(ctx context.Context, flags int32) error {
	_, err := q.db.ExecContext(ctx, resetSectionStarterForSection, flags)
	return err
}

const setSectionStarter = `-- name: SetSectionStarter :one
UPDATE lessons
SET section_starter = $2
WHERE id = $1 and suggested = FALSE
RETURNING id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language
`

type SetSectionStarterParams struct {
	ID             uuid.UUID
	SectionStarter bool
}

func (q *Queries) SetSectionStarter(ctx context.Context, arg SetSectionStarterParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, setSectionStarter, arg.ID, arg.SectionStarter)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
		&i.SectionStarter,
		&i.Suggested,
		&i.ThumbnailID,
		&i.Language,
	)
	return i, err
}

const updateLessonContent = `-- name: UpdateLessonContent :one
UPDATE lessons
SET content_id = $2, updated_at = $3
WHERE id = $1
RETURNING id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language
`

type UpdateLessonContentParams struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	UpdatedAt sql.NullTime
}

func (q *Queries) UpdateLessonContent(ctx context.Context, arg UpdateLessonContentParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, updateLessonContent, arg.ID, arg.ContentID, arg.UpdatedAt)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
		&i.SectionStarter,
		&i.Suggested,
		&i.ThumbnailID,
		&i.Language,
	)
	return i, err
}

const updateLessonDetails = `-- name: UpdateLessonDetails :one
UPDATE lessons
SET title = $2, description = $3, updated_at = $4
WHERE id = $1
RETURNING id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language
`

type UpdateLessonDetailsParams struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	UpdatedAt   sql.NullTime
}

func (q *Queries) UpdateLessonDetails(ctx context.Context, arg UpdateLessonDetailsParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, updateLessonDetails,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.UpdatedAt,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
		&i.SectionStarter,
		&i.Suggested,
		&i.ThumbnailID,
		&i.Language,
	)
	return i, err
}

const updateLessonFlags = `-- name: UpdateLessonFlags :one
UPDATE lessons
SET flags = $2, updated_at = $3
WHERE id = $1
RETURNING id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language
`

type UpdateLessonFlagsParams struct {
	ID        uuid.UUID
	Flags     int32
	UpdatedAt sql.NullTime
}

func (q *Queries) UpdateLessonFlags(ctx context.Context, arg UpdateLessonFlagsParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, updateLessonFlags, arg.ID, arg.Flags, arg.UpdatedAt)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
		&i.SectionStarter,
		&i.Suggested,
		&i.ThumbnailID,
		&i.Language,
	)
	return i, err
}

const updateLessonLanguage = `-- name: UpdateLessonLanguage :one
UPDATE lessons
SET language = $2, updated_at = $3
WHERE id = $1
RETURNING id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language
`

type UpdateLessonLanguageParams struct {
	ID        uuid.UUID
	Language  string
	UpdatedAt sql.NullTime
}

func (q *Queries) UpdateLessonLanguage(ctx context.Context, arg UpdateLessonLanguageParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, updateLessonLanguage, arg.ID, arg.Language, arg.UpdatedAt)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
		&i.SectionStarter,
		&i.Suggested,
		&i.ThumbnailID,
		&i.Language,
	)
	return i, err
}

const updateLessonNext = `-- name: UpdateLessonNext :one
UPDATE lessons
SET next_lesson_id = $2, updated_at = $3
WHERE id = $1
RETURNING id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language
`

type UpdateLessonNextParams struct {
	ID           uuid.UUID
	NextLessonID uuid.NullUUID
	UpdatedAt    sql.NullTime
}

func (q *Queries) UpdateLessonNext(ctx context.Context, arg UpdateLessonNextParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, updateLessonNext, arg.ID, arg.NextLessonID, arg.UpdatedAt)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
		&i.SectionStarter,
		&i.Suggested,
		&i.ThumbnailID,
		&i.Language,
	)
	return i, err
}

const updateLessonPrev = `-- name: UpdateLessonPrev :one
UPDATE lessons
SET prev_lesson_id = $2, updated_at = $3
WHERE id = $1
RETURNING id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language
`

type UpdateLessonPrevParams struct {
	ID           uuid.UUID
	PrevLessonID uuid.NullUUID
	UpdatedAt    sql.NullTime
}

func (q *Queries) UpdateLessonPrev(ctx context.Context, arg UpdateLessonPrevParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, updateLessonPrev, arg.ID, arg.PrevLessonID, arg.UpdatedAt)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
		&i.SectionStarter,
		&i.Suggested,
		&i.ThumbnailID,
		&i.Language,
	)
	return i, err
}

const updateLessonSuggested = `-- name: UpdateLessonSuggested :one
UPDATE lessons
SET suggested = $2, updated_at = $3
WHERE id = $1
RETURNING id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language
`

type UpdateLessonSuggestedParams struct {
	ID        uuid.UUID
	Suggested bool
	UpdatedAt sql.NullTime
}

func (q *Queries) UpdateLessonSuggested(ctx context.Context, arg UpdateLessonSuggestedParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, updateLessonSuggested, arg.ID, arg.Suggested, arg.UpdatedAt)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
		&i.SectionStarter,
		&i.Suggested,
		&i.ThumbnailID,
		&i.Language,
	)
	return i, err
}

const updateLessonThumbnail = `-- name: UpdateLessonThumbnail :one
UPDATE lessons
SET thumbnail_id = $2, updated_at = $3
WHERE id = $1
RETURNING id, title, description, content_id, author_id, created_at, updated_at, flags, next_lesson_id, prev_lesson_id, section_starter, suggested, thumbnail_id, language
`

type UpdateLessonThumbnailParams struct {
	ID          uuid.UUID
	ThumbnailID uuid.NullUUID
	UpdatedAt   sql.NullTime
}

func (q *Queries) UpdateLessonThumbnail(ctx context.Context, arg UpdateLessonThumbnailParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, updateLessonThumbnail, arg.ID, arg.ThumbnailID, arg.UpdatedAt)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flags,
		&i.NextLessonID,
		&i.PrevLessonID,
		&i.SectionStarter,
		&i.Suggested,
		&i.ThumbnailID,
		&i.Language,
	)
	return i, err
}
