// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Filename   string
	Filepath   string
	Filesize   int64
	UploadedAt sql.NullTime
}

type Lesson struct {
	ID           uuid.UUID
	Title        string
	Description  sql.NullString
	ContentID    uuid.UUID
	AuthorID     uuid.NullUUID
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	Flags        int32
	NextLessonID uuid.NullUUID
	PrevLessonID uuid.NullUUID
}

type LessonsUser struct {
	ID          uuid.UUID
	LessonID    uuid.UUID
	UserID      uuid.UUID
	Favorited   bool
	Bookmarked  bool
	StartedAt   sql.NullTime
	CompletedAt sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	PasswordHash   string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	IsAdmin        bool
	ProfilePicID   uuid.NullUUID
	EmailValidated bool
}
