// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CodeTest struct {
	ID             uuid.UUID
	TxtInput       sql.NullString
	FileInput      uuid.NullUUID
	ExpectedOutput string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	NextTestID     uuid.NullUUID
	PreviousTestID uuid.NullUUID
}

type File struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Filename   string
	Filepath   string
	Filesize   int64
	UploadedAt sql.NullTime
}

type Lesson struct {
	ID             uuid.UUID
	Title          string
	Description    sql.NullString
	ContentID      uuid.UUID
	AuthorID       uuid.NullUUID
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Flags          int32
	NextLessonID   uuid.NullUUID
	PrevLessonID   uuid.NullUUID
	SectionStarter bool
	Suggested      bool
	ThumbnailID    uuid.NullUUID
	Language       string
}

type LessonsUser struct {
	ID          uuid.UUID
	LessonID    uuid.UUID
	UserID      uuid.UUID
	Favorited   bool
	Bookmarked  bool
	StartedAt   sql.NullTime
	CompletedAt sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Problem struct {
	ID              uuid.UUID
	Title           string
	Description     string
	Tags            int32
	Source          sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	FirstTest       uuid.NullUUID
	ThumbnailFileID uuid.NullUUID
	AuthorID        uuid.UUID
	Suggested       bool
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Solution struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	ProblemID           uuid.UUID
	FirstSolutionTestID uuid.NullUUID
	SentCode            string
	Language            string
	TestsPassed         sql.NullInt32
	TotalTests          sql.NullInt32
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

type SolutionsTest struct {
	ID                  uuid.UUID
	CodeTestID          uuid.NullUUID
	RunTimeMs           int32
	MemoryUsageKb       int32
	Success             bool
	ErrorMessage        sql.NullString
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	NextSolutionsTestID uuid.NullUUID
	PrevSolutionsTestID uuid.NullUUID
}

type User struct {
	ID               uuid.UUID
	Username         string
	Email            string
	PasswordHash     string
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	ProfilePicID     uuid.NullUUID
	EmailValidated   bool
	CuredEmail       sql.NullString
	Permissions      int16
	Title            string
	TotpSecret       sql.NullString
	Backupcodesecret sql.NullString
}

type UsersProblem struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ProblemID  uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Liked      sql.NullBool
	Bookmarked sql.NullBool
	SolvedAt   sql.NullTime
}
