// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problems.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id
`

type CreateProblemParams struct {
	ID              uuid.UUID
	Title           string
	Description     string
	Tags            int32
	Source          sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	FirstTest       uuid.NullUUID
	ThumbnailFileID uuid.NullUUID
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, createProblem,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FirstTest,
		arg.ThumbnailFileID,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstTest,
		&i.ThumbnailFileID,
		&i.AuthorID,
	)
	return i, err
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id FROM problems
WHERE id = $1
`

func (q *Queries) GetProblemByID(ctx context.Context, id uuid.UUID) (Problem, error) {
	row := q.db.QueryRowContext(ctx, getProblemByID, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstTest,
		&i.ThumbnailFileID,
		&i.AuthorID,
	)
	return i, err
}

const getProblems = `-- name: GetProblems :many
SELECT id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id FROM problems
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetProblemsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetProblems(ctx context.Context, arg GetProblemsParams) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, getProblems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstTest,
			&i.ThumbnailFileID,
			&i.AuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblemsByTag = `-- name: GetProblemsByTag :many
SELECT id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id FROM problems
WHERE $1 & tags = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetProblemsByTagParams struct {
	Tags   int32
	Tags_2 int32
	Limit  int32
	Offset int32
}

// tags is similar to flags, so it's stored as an INT
func (q *Queries) GetProblemsByTag(ctx context.Context, arg GetProblemsByTagParams) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, getProblemsByTag,
		arg.Tags,
		arg.Tags_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstTest,
			&i.ThumbnailFileID,
			&i.AuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
