// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problems.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countProblems = `-- name: CountProblems :one
SELECT COUNT(*) FROM problems
WHERE suggested = FALSE
`

func (q *Queries) CountProblems(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProblems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProblemsByAuthorID = `-- name: CountProblemsByAuthorID :one
SELECT COUNT(*) FROM problems
WHERE author_id = $1 and suggested = FALSE
`

func (q *Queries) CountProblemsByAuthorID(ctx context.Context, authorID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProblemsByAuthorID, authorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProblemsByTag = `-- name: CountProblemsByTag :one
SELECT COUNT(*) FROM problems
WHERE $1 & tags = $2 and suggested = FALSE
`

type CountProblemsByTagParams struct {
	Tags   int32
	Tags_2 int32
}

func (q *Queries) CountProblemsByTag(ctx context.Context, arg CountProblemsByTagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProblemsByTag, arg.Tags, arg.Tags_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id, suggested, total_tests)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id, suggested, total_tests
`

type CreateProblemParams struct {
	ID              uuid.UUID
	Title           string
	Description     string
	Tags            int32
	Source          sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	FirstTest       uuid.NullUUID
	ThumbnailFileID uuid.NullUUID
	AuthorID        uuid.UUID
	Suggested       bool
	TotalTests      int32
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, createProblem,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FirstTest,
		arg.ThumbnailFileID,
		arg.AuthorID,
		arg.Suggested,
		arg.TotalTests,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstTest,
		&i.ThumbnailFileID,
		&i.AuthorID,
		&i.Suggested,
		&i.TotalTests,
	)
	return i, err
}

const deleteProblem = `-- name: DeleteProblem :exec
DELETE FROM problems
WHERE id = $1
`

func (q *Queries) DeleteProblem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProblem, id)
	return err
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id, suggested, total_tests FROM problems
WHERE id = $1
`

func (q *Queries) GetProblemByID(ctx context.Context, id uuid.UUID) (Problem, error) {
	row := q.db.QueryRowContext(ctx, getProblemByID, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstTest,
		&i.ThumbnailFileID,
		&i.AuthorID,
		&i.Suggested,
		&i.TotalTests,
	)
	return i, err
}

const getProblems = `-- name: GetProblems :many
SELECT id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id, suggested, total_tests FROM problems
         WHERE suggested = FALSE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetProblemsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetProblems(ctx context.Context, arg GetProblemsParams) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, getProblems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstTest,
			&i.ThumbnailFileID,
			&i.AuthorID,
			&i.Suggested,
			&i.TotalTests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblemsByAuthorID = `-- name: GetProblemsByAuthorID :many
SELECT id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id, suggested, total_tests FROM problems
WHERE author_id = $1 and suggested = FALSE
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetProblemsByAuthorIDParams struct {
	AuthorID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) GetProblemsByAuthorID(ctx context.Context, arg GetProblemsByAuthorIDParams) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, getProblemsByAuthorID, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstTest,
			&i.ThumbnailFileID,
			&i.AuthorID,
			&i.Suggested,
			&i.TotalTests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblemsBySource = `-- name: GetProblemsBySource :many
SELECT id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id, suggested, total_tests FROM problems
WHERE source = $1 and suggested = FALSE
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetProblemsBySourceParams struct {
	Source sql.NullString
	Limit  int32
	Offset int32
}

func (q *Queries) GetProblemsBySource(ctx context.Context, arg GetProblemsBySourceParams) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, getProblemsBySource, arg.Source, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstTest,
			&i.ThumbnailFileID,
			&i.AuthorID,
			&i.Suggested,
			&i.TotalTests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblemsByTag = `-- name: GetProblemsByTag :many
SELECT id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id, suggested, total_tests FROM problems
WHERE $1 & tags = $2 and suggested = FALSE
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetProblemsByTagParams struct {
	Tags   int32
	Tags_2 int32
	Limit  int32
	Offset int32
}

// tags is similar to flags, so it's stored as an INT
func (q *Queries) GetProblemsByTag(ctx context.Context, arg GetProblemsByTagParams) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, getProblemsByTag,
		arg.Tags,
		arg.Tags_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstTest,
			&i.ThumbnailFileID,
			&i.AuthorID,
			&i.Suggested,
			&i.TotalTests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuggestedProblems = `-- name: GetSuggestedProblems :many
SELECT id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id, suggested, total_tests FROM problems
WHERE suggested = TRUE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetSuggestedProblemsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetSuggestedProblems(ctx context.Context, arg GetSuggestedProblemsParams) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, getSuggestedProblems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstTest,
			&i.ThumbnailFileID,
			&i.AuthorID,
			&i.Suggested,
			&i.TotalTests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProblemDetails = `-- name: UpdateProblemDetails :one
UPDATE problems
SET title = $2, description = $3, source=$4, updated_at = $5
WHERE id = $1
RETURNING id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id, suggested, total_tests
`

type UpdateProblemDetailsParams struct {
	ID          uuid.UUID
	Title       string
	Description string
	Source      sql.NullString
	UpdatedAt   time.Time
}

func (q *Queries) UpdateProblemDetails(ctx context.Context, arg UpdateProblemDetailsParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, updateProblemDetails,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Source,
		arg.UpdatedAt,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstTest,
		&i.ThumbnailFileID,
		&i.AuthorID,
		&i.Suggested,
		&i.TotalTests,
	)
	return i, err
}

const updateProblemFirstTest = `-- name: UpdateProblemFirstTest :one
UPDATE problems
SET first_test = $2, updated_at = $3, total_tests = $4
WHERE id = $1
RETURNING id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id, suggested, total_tests
`

type UpdateProblemFirstTestParams struct {
	ID         uuid.UUID
	FirstTest  uuid.NullUUID
	UpdatedAt  time.Time
	TotalTests int32
}

func (q *Queries) UpdateProblemFirstTest(ctx context.Context, arg UpdateProblemFirstTestParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, updateProblemFirstTest,
		arg.ID,
		arg.FirstTest,
		arg.UpdatedAt,
		arg.TotalTests,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstTest,
		&i.ThumbnailFileID,
		&i.AuthorID,
		&i.Suggested,
		&i.TotalTests,
	)
	return i, err
}

const updateProblemSuggested = `-- name: UpdateProblemSuggested :one
UPDATE problems
SET suggested = $2, updated_at = $3
WHERE id = $1
RETURNING id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id, suggested, total_tests
`

type UpdateProblemSuggestedParams struct {
	ID        uuid.UUID
	Suggested bool
	UpdatedAt time.Time
}

func (q *Queries) UpdateProblemSuggested(ctx context.Context, arg UpdateProblemSuggestedParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, updateProblemSuggested, arg.ID, arg.Suggested, arg.UpdatedAt)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstTest,
		&i.ThumbnailFileID,
		&i.AuthorID,
		&i.Suggested,
		&i.TotalTests,
	)
	return i, err
}

const updateProblemTags = `-- name: UpdateProblemTags :one
UPDATE problems
SET tags = $2, updated_at = $3
WHERE id = $1
RETURNING id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id, suggested, total_tests
`

type UpdateProblemTagsParams struct {
	ID        uuid.UUID
	Tags      int32
	UpdatedAt time.Time
}

func (q *Queries) UpdateProblemTags(ctx context.Context, arg UpdateProblemTagsParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, updateProblemTags, arg.ID, arg.Tags, arg.UpdatedAt)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstTest,
		&i.ThumbnailFileID,
		&i.AuthorID,
		&i.Suggested,
		&i.TotalTests,
	)
	return i, err
}

const updateProblemThumbnail = `-- name: UpdateProblemThumbnail :one
UPDATE problems
SET thumbnail_file_id = $2, updated_at = $3
WHERE id = $1
RETURNING id, title, description, tags, source, created_at, updated_at, first_test, thumbnail_file_id, author_id, suggested, total_tests
`

type UpdateProblemThumbnailParams struct {
	ID              uuid.UUID
	ThumbnailFileID uuid.NullUUID
	UpdatedAt       time.Time
}

func (q *Queries) UpdateProblemThumbnail(ctx context.Context, arg UpdateProblemThumbnailParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, updateProblemThumbnail, arg.ID, arg.ThumbnailFileID, arg.UpdatedAt)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstTest,
		&i.ThumbnailFileID,
		&i.AuthorID,
		&i.Suggested,
		&i.TotalTests,
	)
	return i, err
}
