// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: solutions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countSolutionsByProblemID = `-- name: CountSolutionsByProblemID :one
SELECT COUNT(*) AS count
FROM solutions
WHERE problem_id = $1
`

func (q *Queries) CountSolutionsByProblemID(ctx context.Context, problemID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSolutionsByProblemID, problemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSolutionsByUserID = `-- name: CountSolutionsByUserID :one
SELECT COUNT(*) AS count
FROM solutions
WHERE user_id = $1
`

func (q *Queries) CountSolutionsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSolutionsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSolutionsByUserId = `-- name: CountSolutionsByUserId :one
SELECT COUNT(*) AS count
FROM solutions
WHERE user_id = $1
`

func (q *Queries) CountSolutionsByUserId(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSolutionsByUserId, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserCorrectSolutions = `-- name: CountUserCorrectSolutions :one
SELECT COUNT(*) AS count
FROM solutions
WHERE user_id = $1 AND tests AND tests_passed = total_tests
`

func (q *Queries) CountUserCorrectSolutions(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserCorrectSolutions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserCorrectSolutionsByProblemID = `-- name: CountUserCorrectSolutionsByProblemID :one
SELECT COUNT(*) AS count
FROM solutions
WHERE user_id = $1 AND problem_id = $2 AND tests_passed = total_tests
`

type CountUserCorrectSolutionsByProblemIDParams struct {
	UserID    uuid.UUID
	ProblemID uuid.UUID
}

func (q *Queries) CountUserCorrectSolutionsByProblemID(ctx context.Context, arg CountUserCorrectSolutionsByProblemIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserCorrectSolutionsByProblemID, arg.UserID, arg.ProblemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserSolutionsByProblemID = `-- name: CountUserSolutionsByProblemID :one
SELECT COUNT(*) AS count
FROM solutions
WHERE user_id = $1 AND problem_id = $2
`

type CountUserSolutionsByProblemIDParams struct {
	UserID    uuid.UUID
	ProblemID uuid.UUID
}

func (q *Queries) CountUserSolutionsByProblemID(ctx context.Context, arg CountUserSolutionsByProblemIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserSolutionsByProblemID, arg.UserID, arg.ProblemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSolution = `-- name: CreateSolution :one
INSERT INTO solutions (id, problem_id, user_id, first_solution_test_id, sent_code, language, tests_passed, total_tests, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, problem_id, first_solution_test_id, sent_code, language, tests_passed, total_tests, created_at, updated_at
`

type CreateSolutionParams struct {
	ID                  uuid.UUID
	ProblemID           uuid.UUID
	UserID              uuid.UUID
	FirstSolutionTestID uuid.NullUUID
	SentCode            string
	Language            string
	TestsPassed         sql.NullInt32
	TotalTests          sql.NullInt32
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

func (q *Queries) CreateSolution(ctx context.Context, arg CreateSolutionParams) (Solution, error) {
	row := q.db.QueryRowContext(ctx, createSolution,
		arg.ID,
		arg.ProblemID,
		arg.UserID,
		arg.FirstSolutionTestID,
		arg.SentCode,
		arg.Language,
		arg.TestsPassed,
		arg.TotalTests,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Solution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.FirstSolutionTestID,
		&i.SentCode,
		&i.Language,
		&i.TestsPassed,
		&i.TotalTests,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSolution = `-- name: DeleteSolution :exec
DELETE FROM solutions
WHERE id = $1
`

func (q *Queries) DeleteSolution(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSolution, id)
	return err
}

const getSolutionByID = `-- name: GetSolutionByID :one
SELECT id, user_id, problem_id, first_solution_test_id, sent_code, language, tests_passed, total_tests, created_at, updated_at
FROM solutions
WHERE id = $1
`

func (q *Queries) GetSolutionByID(ctx context.Context, id uuid.UUID) (Solution, error) {
	row := q.db.QueryRowContext(ctx, getSolutionByID, id)
	var i Solution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.FirstSolutionTestID,
		&i.SentCode,
		&i.Language,
		&i.TestsPassed,
		&i.TotalTests,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSolutions = `-- name: GetSolutions :many
SELECT id, user_id, problem_id, first_solution_test_id, sent_code, language, tests_passed, total_tests, created_at, updated_at
FROM solutions
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetSolutionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetSolutions(ctx context.Context, arg GetSolutionsParams) ([]Solution, error) {
	rows, err := q.db.QueryContext(ctx, getSolutions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solution
	for rows.Next() {
		var i Solution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.FirstSolutionTestID,
			&i.SentCode,
			&i.Language,
			&i.TestsPassed,
			&i.TotalTests,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSolutionsByProblemID = `-- name: GetSolutionsByProblemID :many
SELECT id, user_id, problem_id, first_solution_test_id, sent_code, language, tests_passed, total_tests, created_at, updated_at
FROM solutions
WHERE problem_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetSolutionsByProblemIDParams struct {
	ProblemID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) GetSolutionsByProblemID(ctx context.Context, arg GetSolutionsByProblemIDParams) ([]Solution, error) {
	rows, err := q.db.QueryContext(ctx, getSolutionsByProblemID, arg.ProblemID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solution
	for rows.Next() {
		var i Solution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.FirstSolutionTestID,
			&i.SentCode,
			&i.Language,
			&i.TestsPassed,
			&i.TotalTests,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSolutionsByUserID = `-- name: GetSolutionsByUserID :many
SELECT id, user_id, problem_id, first_solution_test_id, sent_code, language, tests_passed, total_tests, created_at, updated_at
FROM solutions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetSolutionsByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetSolutionsByUserID(ctx context.Context, arg GetSolutionsByUserIDParams) ([]Solution, error) {
	rows, err := q.db.QueryContext(ctx, getSolutionsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solution
	for rows.Next() {
		var i Solution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.FirstSolutionTestID,
			&i.SentCode,
			&i.Language,
			&i.TestsPassed,
			&i.TotalTests,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSolutionFirstSolutionTest = `-- name: UpdateSolutionFirstSolutionTest :one
UPDATE solutions
SET first_solution_test_id = $2, updated_at = $3
WHERE id = $1
RETURNING id, user_id, problem_id, first_solution_test_id, sent_code, language, tests_passed, total_tests, created_at, updated_at
`

type UpdateSolutionFirstSolutionTestParams struct {
	ID                  uuid.UUID
	FirstSolutionTestID uuid.NullUUID
	UpdatedAt           sql.NullTime
}

func (q *Queries) UpdateSolutionFirstSolutionTest(ctx context.Context, arg UpdateSolutionFirstSolutionTestParams) (Solution, error) {
	row := q.db.QueryRowContext(ctx, updateSolutionFirstSolutionTest, arg.ID, arg.FirstSolutionTestID, arg.UpdatedAt)
	var i Solution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.FirstSolutionTestID,
		&i.SentCode,
		&i.Language,
		&i.TestsPassed,
		&i.TotalTests,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSolutionTests = `-- name: UpdateSolutionTests :one
UPDATE solutions
SET tests_passed = $2, total_tests = $3, updated_at = $4
WHERE id = $1
RETURNING id, user_id, problem_id, first_solution_test_id, sent_code, language, tests_passed, total_tests, created_at, updated_at
`

type UpdateSolutionTestsParams struct {
	ID          uuid.UUID
	TestsPassed sql.NullInt32
	TotalTests  sql.NullInt32
	UpdatedAt   sql.NullTime
}

func (q *Queries) UpdateSolutionTests(ctx context.Context, arg UpdateSolutionTestsParams) (Solution, error) {
	row := q.db.QueryRowContext(ctx, updateSolutionTests,
		arg.ID,
		arg.TestsPassed,
		arg.TotalTests,
		arg.UpdatedAt,
	)
	var i Solution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.FirstSolutionTestID,
		&i.SentCode,
		&i.Language,
		&i.TestsPassed,
		&i.TotalTests,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
