// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_problems.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countLikesByProblemID = `-- name: CountLikesByProblemID :one
SELECT COUNT(*) AS like_count
FROM users_problems
WHERE problem_id = $1 AND liked = TRUE
`

func (q *Queries) CountLikesByProblemID(ctx context.Context, problemID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLikesByProblemID, problemID)
	var like_count int64
	err := row.Scan(&like_count)
	return like_count, err
}

const countNumberOfSolvedProblemsByUserID = `-- name: CountNumberOfSolvedProblemsByUserID :one
SELECT COUNT(*) AS solved_count
FROM users_problems
WHERE user_id = $1 AND solved_at IS NOT NULL
`

func (q *Queries) CountNumberOfSolvedProblemsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNumberOfSolvedProblemsByUserID, userID)
	var solved_count int64
	err := row.Scan(&solved_count)
	return solved_count, err
}

const countNumberOfSolvesByProblemID = `-- name: CountNumberOfSolvesByProblemID :one
SELECT COUNT(*) AS solve_count
FROM users_problems
WHERE problem_id = $1 AND solved_at IS NOT NULL
`

func (q *Queries) CountNumberOfSolvesByProblemID(ctx context.Context, problemID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNumberOfSolvesByProblemID, problemID)
	var solve_count int64
	err := row.Scan(&solve_count)
	return solve_count, err
}

const createUserProblem = `-- name: CreateUserProblem :one
INSERT INTO users_problems (id, user_id, problem_id, created_at, updated_at, liked, bookmarked, solved_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, problem_id, created_at, updated_at, liked, bookmarked, solved_at
`

type CreateUserProblemParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ProblemID  uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Liked      sql.NullBool
	Bookmarked sql.NullBool
	SolvedAt   sql.NullTime
}

func (q *Queries) CreateUserProblem(ctx context.Context, arg CreateUserProblemParams) (UsersProblem, error) {
	row := q.db.QueryRowContext(ctx, createUserProblem,
		arg.ID,
		arg.UserID,
		arg.ProblemID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Liked,
		arg.Bookmarked,
		arg.SolvedAt,
	)
	var i UsersProblem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Liked,
		&i.Bookmarked,
		&i.SolvedAt,
	)
	return i, err
}

const deleteUserProblem = `-- name: DeleteUserProblem :exec
DELETE FROM users_problems
WHERE user_id = $1 AND problem_id = $2
`

type DeleteUserProblemParams struct {
	UserID    uuid.UUID
	ProblemID uuid.UUID
}

func (q *Queries) DeleteUserProblem(ctx context.Context, arg DeleteUserProblemParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserProblem, arg.UserID, arg.ProblemID)
	return err
}

const getBookmarkedProblemsByUserID = `-- name: GetBookmarkedProblemsByUserID :many
SELECT id, user_id, problem_id, created_at, updated_at, liked, bookmarked, solved_at
FROM users_problems
WHERE user_id = $1 AND bookmarked = TRUE
`

func (q *Queries) GetBookmarkedProblemsByUserID(ctx context.Context, userID uuid.UUID) ([]UsersProblem, error) {
	rows, err := q.db.QueryContext(ctx, getBookmarkedProblemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersProblem
	for rows.Next() {
		var i UsersProblem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Liked,
			&i.Bookmarked,
			&i.SolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikedProblemsByUserID = `-- name: GetLikedProblemsByUserID :many
SELECT id, user_id, problem_id, created_at, updated_at, liked, bookmarked, solved_at
FROM users_problems
WHERE user_id = $1 AND liked = TRUE
`

func (q *Queries) GetLikedProblemsByUserID(ctx context.Context, userID uuid.UUID) ([]UsersProblem, error) {
	rows, err := q.db.QueryContext(ctx, getLikedProblemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersProblem
	for rows.Next() {
		var i UsersProblem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Liked,
			&i.Bookmarked,
			&i.SolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSolvedProblemsByUserID = `-- name: GetSolvedProblemsByUserID :many
SELECT id, user_id, problem_id, created_at, updated_at, liked, bookmarked, solved_at
FROM users_problems
WHERE user_id = $1 AND solved_at IS NOT NULL
`

func (q *Queries) GetSolvedProblemsByUserID(ctx context.Context, userID uuid.UUID) ([]UsersProblem, error) {
	rows, err := q.db.QueryContext(ctx, getSolvedProblemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersProblem
	for rows.Next() {
		var i UsersProblem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Liked,
			&i.Bookmarked,
			&i.SolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProblemByUserIDAndProblemID = `-- name: GetUserProblemByUserIDAndProblemID :one
SELECT id, user_id, problem_id, created_at, updated_at, liked, bookmarked, solved_at
FROM users_problems
WHERE user_id = $1 AND problem_id = $2
`

type GetUserProblemByUserIDAndProblemIDParams struct {
	UserID    uuid.UUID
	ProblemID uuid.UUID
}

func (q *Queries) GetUserProblemByUserIDAndProblemID(ctx context.Context, arg GetUserProblemByUserIDAndProblemIDParams) (UsersProblem, error) {
	row := q.db.QueryRowContext(ctx, getUserProblemByUserIDAndProblemID, arg.UserID, arg.ProblemID)
	var i UsersProblem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Liked,
		&i.Bookmarked,
		&i.SolvedAt,
	)
	return i, err
}

const getUserProblemsByUserID = `-- name: GetUserProblemsByUserID :many
SELECT id, user_id, problem_id, created_at, updated_at, liked, bookmarked, solved_at
FROM users_problems
WHERE user_id = $1
`

func (q *Queries) GetUserProblemsByUserID(ctx context.Context, userID uuid.UUID) ([]UsersProblem, error) {
	rows, err := q.db.QueryContext(ctx, getUserProblemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersProblem
	for rows.Next() {
		var i UsersProblem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Liked,
			&i.Bookmarked,
			&i.SolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProblemBookmark = `-- name: UpdateUserProblemBookmark :one
UPDATE users_problems
SET bookmarked = $1, updated_at = $2
WHERE user_id = $3 AND problem_id = $4
RETURNING id, user_id, problem_id, created_at, updated_at, liked, bookmarked, solved_at
`

type UpdateUserProblemBookmarkParams struct {
	Bookmarked sql.NullBool
	UpdatedAt  time.Time
	UserID     uuid.UUID
	ProblemID  uuid.UUID
}

func (q *Queries) UpdateUserProblemBookmark(ctx context.Context, arg UpdateUserProblemBookmarkParams) (UsersProblem, error) {
	row := q.db.QueryRowContext(ctx, updateUserProblemBookmark,
		arg.Bookmarked,
		arg.UpdatedAt,
		arg.UserID,
		arg.ProblemID,
	)
	var i UsersProblem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Liked,
		&i.Bookmarked,
		&i.SolvedAt,
	)
	return i, err
}

const updateUserProblemLike = `-- name: UpdateUserProblemLike :one
UPDATE users_problems
SET liked = $1, updated_at = $2
WHERE user_id = $3 AND problem_id = $4
RETURNING id, user_id, problem_id, created_at, updated_at, liked, bookmarked, solved_at
`

type UpdateUserProblemLikeParams struct {
	Liked     sql.NullBool
	UpdatedAt time.Time
	UserID    uuid.UUID
	ProblemID uuid.UUID
}

func (q *Queries) UpdateUserProblemLike(ctx context.Context, arg UpdateUserProblemLikeParams) (UsersProblem, error) {
	row := q.db.QueryRowContext(ctx, updateUserProblemLike,
		arg.Liked,
		arg.UpdatedAt,
		arg.UserID,
		arg.ProblemID,
	)
	var i UsersProblem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Liked,
		&i.Bookmarked,
		&i.SolvedAt,
	)
	return i, err
}

const updateUserProblemSolvedAt = `-- name: UpdateUserProblemSolvedAt :one
UPDATE users_problems
SET solved_at = $1, updated_at = $2
WHERE user_id = $3 AND problem_id = $4
RETURNING id, user_id, problem_id, created_at, updated_at, liked, bookmarked, solved_at
`

type UpdateUserProblemSolvedAtParams struct {
	SolvedAt  sql.NullTime
	UpdatedAt time.Time
	UserID    uuid.UUID
	ProblemID uuid.UUID
}

func (q *Queries) UpdateUserProblemSolvedAt(ctx context.Context, arg UpdateUserProblemSolvedAtParams) (UsersProblem, error) {
	row := q.db.QueryRowContext(ctx, updateUserProblemSolvedAt,
		arg.SolvedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.ProblemID,
	)
	var i UsersProblem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Liked,
		&i.Bookmarked,
		&i.SolvedAt,
	)
	return i, err
}
