// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_activities.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUsersActivities = `-- name: CreateUsersActivities :one
INSERT INTO users_activities (user_id, xp_gained, activity_type, created_at, updated_at, id)
    VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, xp_gained, activity_type, created_at, updated_at
`

type CreateUsersActivitiesParams struct {
	UserID       uuid.UUID
	XpGained     int32
	ActivityType string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ID           uuid.UUID
}

func (q *Queries) CreateUsersActivities(ctx context.Context, arg CreateUsersActivitiesParams) (UsersActivity, error) {
	row := q.db.QueryRowContext(ctx, createUsersActivities,
		arg.UserID,
		arg.XpGained,
		arg.ActivityType,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i UsersActivity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.XpGained,
		&i.ActivityType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserActivitiesByUserId = `-- name: DeleteUserActivitiesByUserId :exec
DELETE FROM users_activities
WHERE user_id = $1
`

func (q *Queries) DeleteUserActivitiesByUserId(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserActivitiesByUserId, userID)
	return err
}

const getUserActivities = `-- name: GetUserActivities :many
SELECT id, user_id, xp_gained, activity_type, created_at, updated_at FROM users_activities
WHERE user_id = $1 AND created_at >= $2 AND created_at <= $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type GetUserActivitiesParams struct {
	UserID      uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	Limit       int32
	Offset      int32
}

func (q *Queries) GetUserActivities(ctx context.Context, arg GetUserActivitiesParams) ([]UsersActivity, error) {
	rows, err := q.db.QueryContext(ctx, getUserActivities,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersActivity
	for rows.Next() {
		var i UsersActivity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.XpGained,
			&i.ActivityType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActivitiesByType = `-- name: GetUserActivitiesByType :many
SELECT id, user_id, xp_gained, activity_type, created_at, updated_at FROM users_activities
WHERE user_id = $1 AND activity_type = $2 AND created_at >= $3 AND created_at <= $4
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type GetUserActivitiesByTypeParams struct {
	UserID       uuid.UUID
	ActivityType string
	CreatedAt    time.Time
	CreatedAt_2  time.Time
	Limit        int32
	Offset       int32
}

func (q *Queries) GetUserActivitiesByType(ctx context.Context, arg GetUserActivitiesByTypeParams) ([]UsersActivity, error) {
	rows, err := q.db.QueryContext(ctx, getUserActivitiesByType,
		arg.UserID,
		arg.ActivityType,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersActivity
	for rows.Next() {
		var i UsersActivity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.XpGained,
			&i.ActivityType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActivityById = `-- name: GetUserActivityById :one
SELECT id, user_id, xp_gained, activity_type, created_at, updated_at FROM users_activities
WHERE id = $1
`

func (q *Queries) GetUserActivityById(ctx context.Context, id uuid.UUID) (UsersActivity, error) {
	row := q.db.QueryRowContext(ctx, getUserActivityById, id)
	var i UsersActivity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.XpGained,
		&i.ActivityType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
