// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_activities.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUserActivitiesByType = `-- name: CountUserActivitiesByType :one
SELECT COUNT(*) AS activity_count FROM users_activities
WHERE user_id = $1 AND activity_type = $2 AND created_at >= $3 AND created_at <= $4
`

type CountUserActivitiesByTypeParams struct {
	UserID       uuid.UUID
	ActivityType string
	CreatedAt    time.Time
	CreatedAt_2  time.Time
}

func (q *Queries) CountUserActivitiesByType(ctx context.Context, arg CountUserActivitiesByTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserActivitiesByType,
		arg.UserID,
		arg.ActivityType,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	var activity_count int64
	err := row.Scan(&activity_count)
	return activity_count, err
}

const createUsersActivities = `-- name: CreateUsersActivities :one
INSERT INTO users_activities (user_id, xp_gained, activity_type, created_at, updated_at, id)
    VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, xp_gained, activity_type, created_at, updated_at
`

type CreateUsersActivitiesParams struct {
	UserID       uuid.UUID
	XpGained     int32
	ActivityType string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ID           uuid.UUID
}

func (q *Queries) CreateUsersActivities(ctx context.Context, arg CreateUsersActivitiesParams) (UsersActivity, error) {
	row := q.db.QueryRowContext(ctx, createUsersActivities,
		arg.UserID,
		arg.XpGained,
		arg.ActivityType,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i UsersActivity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.XpGained,
		&i.ActivityType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserActivitiesByUserId = `-- name: DeleteUserActivitiesByUserId :exec
DELETE FROM users_activities
WHERE user_id = $1
`

func (q *Queries) DeleteUserActivitiesByUserId(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserActivitiesByUserId, userID)
	return err
}

const getLastUserActivity = `-- name: GetLastUserActivity :one
SELECT id, user_id, xp_gained, activity_type, created_at, updated_at FROM users_activities
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastUserActivity(ctx context.Context, userID uuid.UUID) (UsersActivity, error) {
	row := q.db.QueryRowContext(ctx, getLastUserActivity, userID)
	var i UsersActivity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.XpGained,
		&i.ActivityType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserActivities = `-- name: GetUserActivities :many
SELECT id, user_id, xp_gained, activity_type, created_at, updated_at FROM users_activities
WHERE user_id = $1 AND created_at >= $2 AND created_at <= $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type GetUserActivitiesParams struct {
	UserID      uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	Limit       int32
	Offset      int32
}

func (q *Queries) GetUserActivities(ctx context.Context, arg GetUserActivitiesParams) ([]UsersActivity, error) {
	rows, err := q.db.QueryContext(ctx, getUserActivities,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersActivity
	for rows.Next() {
		var i UsersActivity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.XpGained,
			&i.ActivityType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActivitiesByType = `-- name: GetUserActivitiesByType :many
SELECT id, user_id, xp_gained, activity_type, created_at, updated_at FROM users_activities
WHERE user_id = $1 AND activity_type = $2 AND created_at >= $3 AND created_at <= $4
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type GetUserActivitiesByTypeParams struct {
	UserID       uuid.UUID
	ActivityType string
	CreatedAt    time.Time
	CreatedAt_2  time.Time
	Limit        int32
	Offset       int32
}

func (q *Queries) GetUserActivitiesByType(ctx context.Context, arg GetUserActivitiesByTypeParams) ([]UsersActivity, error) {
	rows, err := q.db.QueryContext(ctx, getUserActivitiesByType,
		arg.UserID,
		arg.ActivityType,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersActivity
	for rows.Next() {
		var i UsersActivity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.XpGained,
			&i.ActivityType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActivitiesGroupedByDays = `-- name: GetUserActivitiesGroupedByDays :many
SELECT DATE_TRUNC('day', created_at) AS day, ARRAY_AGG(users_activities) AS activities
FROM users_activities
WHERE user_id = $1 AND created_at >= $2 AND created_at <= $3
GROUP BY day
ORDER BY day ASC
LIMIT $4 OFFSET $5
`

type GetUserActivitiesGroupedByDaysParams struct {
	UserID      uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	Limit       int32
	Offset      int32
}

type GetUserActivitiesGroupedByDaysRow struct {
	Day        int64
	Activities interface{}
}

func (q *Queries) GetUserActivitiesGroupedByDays(ctx context.Context, arg GetUserActivitiesGroupedByDaysParams) ([]GetUserActivitiesGroupedByDaysRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserActivitiesGroupedByDays,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserActivitiesGroupedByDaysRow
	for rows.Next() {
		var i GetUserActivitiesGroupedByDaysRow
		if err := rows.Scan(&i.Day, &i.Activities); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActivityById = `-- name: GetUserActivityById :one
SELECT id, user_id, xp_gained, activity_type, created_at, updated_at FROM users_activities
WHERE id = $1
`

func (q *Queries) GetUserActivityById(ctx context.Context, id uuid.UUID) (UsersActivity, error) {
	row := q.db.QueryRowContext(ctx, getUserActivityById, id)
	var i UsersActivity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.XpGained,
		&i.ActivityType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserStreak = `-- name: GetUserStreak :one
SELECT current_streak FROM users
WHERE id = $1
`

func (q *Queries) GetUserStreak(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserStreak, id)
	var current_streak int32
	err := row.Scan(&current_streak)
	return current_streak, err
}

const resetUserStreak = `-- name: ResetUserStreak :exec
UPDATE users
SET current_streak = 0
WHERE id = $1
`

func (q *Queries) ResetUserStreak(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resetUserStreak, id)
	return err
}

const sumXpGainedByUserId = `-- name: SumXpGainedByUserId :one
SELECT COALESCE(SUM(xp_gained), 0) AS total_xp FROM users_activities
WHERE user_id = $1 AND created_at >= $2 AND created_at <= $3
`

type SumXpGainedByUserIdParams struct {
	UserID      uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

func (q *Queries) SumXpGainedByUserId(ctx context.Context, arg SumXpGainedByUserIdParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumXpGainedByUserId, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	var total_xp interface{}
	err := row.Scan(&total_xp)
	return total_xp, err
}

const sumXpGainedByUserIdAndType = `-- name: SumXpGainedByUserIdAndType :one
SELECT COALESCE(SUM(xp_gained), 0) AS total_xp FROM users_activities
WHERE user_id = $1 AND activity_type = $2 AND created_at >= $3 AND created_at <= $4
`

type SumXpGainedByUserIdAndTypeParams struct {
	UserID       uuid.UUID
	ActivityType string
	CreatedAt    time.Time
	CreatedAt_2  time.Time
}

func (q *Queries) SumXpGainedByUserIdAndType(ctx context.Context, arg SumXpGainedByUserIdAndTypeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumXpGainedByUserIdAndType,
		arg.UserID,
		arg.ActivityType,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	var total_xp interface{}
	err := row.Scan(&total_xp)
	return total_xp, err
}

const sumXpGainedGroupedByDays = `-- name: SumXpGainedGroupedByDays :many
SELECT DATE_TRUNC('day', created_at) AS day, COALESCE(SUM(xp_gained), 0) AS total_xp
FROM users_activities
WHERE user_id = $1 AND created_at >= $2 AND created_at <= $3
GROUP BY day
ORDER BY day ASC
LIMIT $4 OFFSET $5
`

type SumXpGainedGroupedByDaysParams struct {
	UserID      uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	Limit       int32
	Offset      int32
}

type SumXpGainedGroupedByDaysRow struct {
	Day     int64
	TotalXp interface{}
}

func (q *Queries) SumXpGainedGroupedByDays(ctx context.Context, arg SumXpGainedGroupedByDaysParams) ([]SumXpGainedGroupedByDaysRow, error) {
	rows, err := q.db.QueryContext(ctx, sumXpGainedGroupedByDays,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumXpGainedGroupedByDaysRow
	for rows.Next() {
		var i SumXpGainedGroupedByDaysRow
		if err := rows.Scan(&i.Day, &i.TotalXp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserStreak = `-- name: UpdateUserStreak :one
UPDATE users
SET current_streak = current_streak + 1
WHERE id = $1
RETURNING current_streak
`

// This function works on the users table, but it's related to user activities
// Hence future me get bamboozled <3
func (q *Queries) UpdateUserStreak(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateUserStreak, id)
	var current_streak int32
	err := row.Scan(&current_streak)
	return current_streak, err
}
